# Generated by Django 3.1.7 on 2021-05-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_request',
            name='is_friends',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
