# Generated by Django 3.1.7 on 2021-05-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Friend', '0002_auto_20210513_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend_request',
            name='is_friends',
        ),
    ]
